server:
  host: 'localhost'
  port: 3030
  httpsPort: false
  exclude: ['**/*.spec.ts', '**/*.spec.js', '**/index.ts']
  mount:
    '/': '${rootDir}/controller/*.js'
  componentsScan: [
    '${rootDir}/middleware/*.js',
    '${rootDir}/service/*.js',
    '${rootDir}/protocol/**/*.js'
  ]

jwt:
  secret: 'YOUR_SECRET_KEY'
  expiresIn: '2 days'
  issuer: 'Issuer'
  audience: "example.net"
                                                                            
db:
  mysql: 
    host: 'YOUR_HOST'
    port: 3306
    user: 'YOUR_USER_NAME'
    password: 'YOUR_PASSWORD'
    database: 'YOUR_DATABASE'
    debug: false
  